server:
  port: 8081
  #use-forward-headers: false
  servlet:
    context-path: /ms-got
  compression: 
    enabled: false

auth-server:
  url: http://auth:8085
  #url: http://zuul:8060/uaa
  
#security:
#  oauth2:
#    resource:
#      userInfoUri: 

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  server: 
    wait-time-in-ms-when-sync-empty: 3000

management:
  security:
    enabled: false
    
spring:
  application:
    name: ms-got
  datasource:
    url: jdbc:postgresql://postgres:${POSTGRES_PORT}/oauth2?currentSchema=public
#${MSGOT_DB}?currentSchema=public
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: create
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      indent-output: true

#oauth:
#  datasource:
#    url: jdbc:postgresql://postgres:${POSTGRES_PORT}/oauth2?currentSchema=public
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#    tomcat:
#      test-while-idle: true
#      validation-query: SELECT 1
#    initialization-mode: never
#    platform: postgres
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#    hibernate:
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      ddl-auto: create
#  jackson:
#    property-naming-strategy: SNAKE_CASE
#    serialization:
#      indent-output: true

logging:
  level:
    ROOT: DEBUG
    eu.babywatcher: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG 
    eu.babywarcher: DEBUG
  file: /tmp/logs/ms-got.log
  pattern: 
    #console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"    
